# Generated by Django 5.1.6 on 2025-03-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_size_rename_last_modified_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
